<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 3.2.2 (Python 3.7.3 on win32)" generated="20210523 17:17:27.663" rpa="false">
<suite id="s1" name="测试点击分类2" source="D:\LTTest_Study\AppAutoRobot\testcases\测试点击分类2.robot">
<test id="s1-t1" name="测试点击分类">
<kw name="启动小米商城">
<arguments>
<arg>${appium_server}</arg>
<arg>${MuMu}</arg>
</arguments>
<msg timestamp="20210523 17:17:28.072" level="FAIL">No keyword with name '启动小米商城' found.</msg>
<status status="FAIL" starttime="20210523 17:17:28.072" endtime="20210523 17:17:28.072"></status>
</kw>
<status status="FAIL" starttime="20210523 17:17:28.067" endtime="20210523 17:17:28.072" critical="yes">No keyword with name '启动小米商城' found.</status>
</test>
<status status="FAIL" starttime="20210523 17:17:27.668" endtime="20210523 17:17:28.073"></status>
</suite>
<statistics>
<total>
<stat pass="0" fail="1">Critical Tests</stat>
<stat pass="0" fail="1">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" id="s1" name="测试点击分类2">测试点击分类2</stat>
</suite>
</statistics>
<errors>
<msg timestamp="20210523 17:17:28.036" level="ERROR">Error in file 'D:\LTTest_Study\AppAutoRobot\testcases\测试点击分类2.robot' on line 3: Resource file '基础操作.robot' does not exist.</msg>
<msg timestamp="20210523 17:17:28.063" level="ERROR">Error in file 'D:\LTTest_Study\AppAutoRobot\testcases\测试点击分类2.robot' on line 4: Resource file '分类页.robot' does not exist.</msg>
<msg timestamp="20210523 17:17:28.064" level="ERROR">Error in file 'D:\LTTest_Study\AppAutoRobot\testcases\测试点击分类2.robot' on line 5: Resource file '首页.robot' does not exist.</msg>
<msg timestamp="20210523 17:17:28.066" level="ERROR">Error in file 'D:\LTTest_Study\AppAutoRobot\testcases\测试点击分类2.robot' on line 6: Resource file 'data\config.robot' does not exist.</msg>
</errors>
</robot>
